# Generated by Django 5.2.4 on 2025-08-05 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('description', models.TextField(blank=True)),
                ('prep_time', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(120)])),
                ('cook_time', models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(120)])),
                ('ingredients', models.TextField()),
                ('calories', models.PositiveIntegerField()),
                ('cooking_instructions', models.TextField()),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Vegetarian', 'Vegetarian'), ('BBQ GRILL', 'BBQ GRILL'), ('Snack', 'Snack'), ('Protein Shake', 'Protein Shake')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=110, null=True, unique=True)),
            ],
        ),
    ]
