# Generated by Django 5.2.4 on 2025-07-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_mealplan_day_alter_workoutplan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='meal_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20),
        ),
    ]
