# Generated by Django 5.2.4 on 2025-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_mealplan_meal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(choices=[('30‑Day Challenge', 'Thirty Days'), ('60‑Day Transformation', 'Sixty Days'), ('90‑Day Champion', 'Ninety Days')], unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='goals/')),
            ],
        ),
    ]
