# Generated by Django 5.2.4 on 2025-07-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_goalplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.goalplan'),
        ),
    ]
