# Generated by Django 5.2.4 on 2025-07-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_userprofile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalplan',
            name='length',
            field=models.CharField(choices=[('30‑Day Challenge', 'Thirty Days'), ('60‑Day Transformation', 'Sixty Days'), ('90‑Day Champion', 'Ninety Days')], unique=True),
        ),
    ]
