# Generated by Django 5.2.4 on 2025-07-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_goalplan_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalplan',
            name='length',
            field=models.CharField(choices=[('30-Day', '30‑Day Challenge'), ('60-Day', '60‑Day Transformation'), ('90-Day', '90‑Day Champion')], max_length=20, unique=True),
        ),
    ]
