# Generated by Django 5.2.4 on 2025-07-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_seed_goalplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fitness_goal',
        ),
    ]
