# Generated by Django 5.2.4 on 2025-07-23 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_userprofile_fitness_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='cooking_instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
    ]
