# Generated by Django 5.2.4 on 2025-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_recipe_name_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
