# Generated by Django 5.2.4 on 2025-07-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_recipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipe',
            field=models.ForeignKey(default=3123, on_delete=django.db.models.deletion.CASCADE, to='common.recipe'),
            preserve_default=False,
        ),
    ]
