# Generated by Django 5.2.4 on 2025-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_mealplan_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_time',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_choice',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Vegetarian', 'Vegetarian'), ('BBQ GRILL', 'BBQ GRILL'), ('Snack', 'Snack'), ('Protein Shake', 'Protein Shake')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
