# Generated by Django 5.2.4 on 2025-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_workout_equipment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
