# Generated by Django 5.2.4 on 2025-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_workout_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise/')),
                ('description', models.TextField(blank=True)),
                ('workout_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12)),
                ('time_per_workout', models.PositiveIntegerField()),
                ('equipment_required', models.CharField(max_length=100)),
                ('exercises', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
