# Generated by Django 5.2.4 on 2025-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_exercise_delete_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercises',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='time_per_workout',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_muscle_group',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment_required',
            field=models.CharField(max_length=50),
        ),
    ]
