# Generated by Django 5.2.4 on 2025-07-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_rename_exercises_exercise_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='user',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='name',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workout_type',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
