# Generated by Django 5.2.4 on 2025-07-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_rename_user_workoutexercise_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='title',
        ),
    ]
