# Generated by Django 5.2.4 on 2025-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_exercise_target_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Abs', 'Abs'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Cardio', 'Cardio')], max_length=20),
        ),
    ]
