# Generated by Django 5.2.4 on 2025-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=110, unique=True),
            preserve_default=False,
        ),
    ]
