# Generated by Django 5.2.4 on 2025-07-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_alter_exercise_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='workout_type',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
