# Generated by Django 5.2.4 on 2025-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_alter_exercise_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='workout_type',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
