# Generated by Django 5.2.4 on 2025-07-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_alter_workoutplan_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout_type',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
