# Generated by Django 5.2.4 on 2025-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_alter_workoutexercise_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Vegetarian', 'Vegetarian'), ('BBQ GRILL', 'BBQ GRILL'), ('Snack', 'Snack'), ('Protein Shake', 'Protein Shake')], default='Breakfast', max_length=20),
        ),
    ]
