# Generated by Django 5.2.4 on 2025-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Vegetarian', 'Vegetarian'), ('BBQ GRILL', 'BBQ GRILL'), ('Snack', 'Snack'), ('Protein Shake', 'Protein Shake')], max_length=20),
        ),
    ]
