# Generated by Django 5.2.4 on 2025-08-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
