# Generated by Django 5.2.4 on 2025-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise/')),
                ('target_muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Abs', 'Abs'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Cardio', 'Cardio')], max_length=20)),
                ('equipment_required', models.CharField(max_length=50)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('overview', models.TextField()),
                ('instructions', models.TextField()),
                ('tips', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
        ),
    ]
