# Generated by Django 5.2.4 on 2025-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
